import { LanguageOption } from "./types";

// Reordered to prioritize English + Major Indian Languages first
export const SUPPORTED_LANGUAGES: LanguageOption[] = [
  { code: 'en', name: 'English', nativeName: 'English' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ' },
  { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം' },
  { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ' },
  { code: 'ur', name: 'Urdu', nativeName: 'اردو' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা' },
  // International Languages
  { code: 'es', name: 'Spanish', nativeName: 'Español' },
  { code: 'fr', name: 'French', nativeName: 'Français' },
  { code: 'ar', name: 'Arabic', nativeName: 'العربية' },
  { code: 'zh', name: 'Chinese', nativeName: '中文' },
  { code: 'pt', name: 'Portuguese', nativeName: 'Português' },
  { code: 'ru', name: 'Russian', nativeName: 'Русский' },
  { code: 'de', name: 'German', nativeName: 'Deutsch' },
  { code: 'ja', name: 'Japanese', nativeName: '日本語' },
];

export const PLAYBACK_SPEEDS = [0.5, 0.75, 1.0, 1.25, 1.5, 2.0];

export const UI_TRANSLATIONS: Record<string, any> = {
  en: {
    appTitle: "DocuVoice",
    appSubtitle: "Upload, Translate, and Listen.",
    selectLanguage: "Select Output Language",
    showMore: "Show all languages",
    showLess: "Show less",
    history: "History",
    noHistory: "No translation history yet.",
    step1: "Upload Document",
    uploadPrompt: "Click to upload Bill, GO Form, or Document",
    uploadSupport: "Supports PDF, JPG, PNG",
    changeFile: "Click to change file",
    optimizing: "Optimizing image...",
    step2: "Choose Language",
    generateAudio: "Generate Audio",
    viewHistoryPrompt: "Viewing history. Generate audio to listen?",
    summaryTitle: "Simplified Summary",
    officialDetails: "Official Document Details",
    officialTag: "Official",
    locationTitle: "Document Location",
    openMaps: "Open Maps",
    fullTranslation: "Full Translated Document",
    highlightTip: "Highlight text to save",
    download: "Download",
    actionItemsTitle: "What you need to do",
    savedHighlights: "Saved Highlights",
    startOver: "Start Over",
    fastMode: "Fast",
    fastModeDesc: "Best for printed text",
    detailedMode: "Deep Reasoning",
    detailedModeDesc: "Best for complex forms",
    translateBtn: "Translate & Read Aloud",
    analyzing: "Analyzing Document...",
    findingLocation: "Finding Location...",
    generating: "Generating Audio...",
    audioPlayer: {
      title: "Voice Reader",
      restart: "Restart",
      play: "Read Aloud",
      pause: "Pause",
      speed: "Speed",
      statusPlaying: "Reading document...",
      statusIdle: "Press play to listen"
    }
  },
  es: {
    appTitle: "DocuVoice",
    appSubtitle: "Subir, Traducir y Escuchar.",
    selectLanguage: "Seleccionar Idioma de Salida",
    showMore: "Mostrar todos",
    showLess: "Mostrar menos",
    history: "Historial",
    noHistory: "No hay historial aún.",
    step1: "Subir Documento",
    uploadPrompt: "Clic para subir Factura, Formulario o Documento",
    uploadSupport: "Soporta PDF, JPG, PNG",
    changeFile: "Clic para cambiar archivo",
    optimizing: "Optimizando imagen...",
    step2: "Elegir Idioma",
    generateAudio: "Generar Audio",
    viewHistoryPrompt: "Viendo historial. ¿Generar audio?",
    summaryTitle: "Resumen Simplificado",
    officialDetails: "Detalles del Documento Oficial",
    officialTag: "Oficial",
    locationTitle: "Ubicación del Documento",
    openMaps: "Abrir Mapas",
    fullTranslation: "Documento Traducido",
    highlightTip: "Resalta texto para guardar",
    download: "Descargar",
    actionItemsTitle: "Lo que necesitas hacer",
    savedHighlights: "Destacados Guardados",
    startOver: "Empezar de Nuevo",
    fastMode: "Rápido",
    fastModeDesc: "Mejor para texto impreso",
    detailedMode: "Razonamiento",
    detailedModeDesc: "Mejor para formularios complejos",
    translateBtn: "Traducir y Leer",
    analyzing: "Analizando Documento...",
    findingLocation: "Buscando Ubicación...",
    generating: "Generando Audio...",
    audioPlayer: {
      title: "Lector de Voz",
      restart: "Reiniciar",
      play: "Leer",
      pause: "Pausa",
      speed: "Velocidad",
      statusPlaying: "Leyendo documento...",
      statusIdle: "Pulsa reproducir para escuchar"
    }
  },
  fr: {
    appTitle: "DocuVoice",
    appSubtitle: "Télécharger, Traduire et Écouter.",
    selectLanguage: "Choisir la langue de sortie",
    showMore: "Tout afficher",
    showLess: "Montrer moins",
    history: "Historique",
    noHistory: "Pas encore d'historique.",
    step1: "Télécharger le Document",
    uploadPrompt: "Cliquez pour télécharger Facture, Formulaire ou Document",
    uploadSupport: "Supporte PDF, JPG, PNG",
    changeFile: "Cliquez pour changer de fichier",
    optimizing: "Optimisation de l'image...",
    step2: "Choisir la Langue",
    generateAudio: "Générer l'audio",
    viewHistoryPrompt: "Historique. Générer l'audio ?",
    summaryTitle: "Résumé Simplifié",
    officialDetails: "Détails du Document Officiel",
    officialTag: "Officiel",
    locationTitle: "Emplacement du Document",
    openMaps: "Ouvrir Maps",
    fullTranslation: "Traduction Complète",
    highlightTip: "Surligner pour sauvegarder",
    download: "Télécharger",
    actionItemsTitle: "Ce que vous devez faire",
    savedHighlights: "Points Forts Enregistrés",
    startOver: "Recommencer",
    fastMode: "Rapide",
    fastModeDesc: "Pour texte imprimé",
    detailedMode: "Raisonnement",
    detailedModeDesc: "Pour formulaires complexes",
    translateBtn: "Traduire et Lire",
    analyzing: "Analyse en cours...",
    findingLocation: "Localisation...",
    generating: "Génération Audio...",
    audioPlayer: {
      title: "Lecteur Vocal",
      restart: "Redémarrer",
      play: "Lire",
      pause: "Pause",
      speed: "Vitesse",
      statusPlaying: "Lecture du document...",
      statusIdle: "Appuyez sur lecture"
    }
  },
  hi: {
    appTitle: "DocuVoice",
    appSubtitle: "अपलोड करें, अनुवाद करें और सुनें।",
    selectLanguage: "आउटपुट भाषा चुनें",
    showMore: "सभी दिखाएं",
    showLess: "कम दिखाएं",
    history: "इतिहास",
    noHistory: "कोई अनुवाद इतिहास नहीं।",
    step1: "दस्तावेज़ अपलोड करें",
    uploadPrompt: "बिल, फॉर्म या दस्तावेज़ अपलोड करने के लिए क्लिक करें",
    uploadSupport: "PDF, JPG, PNG समर्थित",
    changeFile: "फ़ाइल बदलने के लिए क्लिक करें",
    optimizing: "छवि अनुकूलित की जा रही है...",
    step2: "भाषा चुनें",
    generateAudio: "ऑडियो बनाएं",
    viewHistoryPrompt: "इतिहास देख रहे हैं। सुनने के लिए ऑडियो बनाएं?",
    summaryTitle: "सरलीकृत सारांश",
    officialDetails: "आधिकारिक दस्तावेज़ विवरण",
    officialTag: "आधिकारिक",
    locationTitle: "दस्तावेज़ स्थान",
    openMaps: "मैप्स खोलें",
    fullTranslation: "पूरा अनुवादित दस्तावेज़",
    highlightTip: "सहेजने के लिए टेक्स्ट हाइलाइट करें",
    download: "डाउनलोड",
    actionItemsTitle: "आपको क्या करना है",
    savedHighlights: "सहेजे गए हाइलाइट्स",
    startOver: "फिर से शुरू करें",
    fastMode: "तेज़",
    fastModeDesc: "साफ़ टेक्स्ट के लिए सर्वोत्तम",
    detailedMode: "गहन तर्क",
    detailedModeDesc: "जटिल फॉर्म के लिए सर्वोत्तम",
    translateBtn: "अनुवाद करें और सुनें",
    analyzing: "दस्तावेज़ का विश्लेषण...",
    findingLocation: "स्थान ढूँढ रहा है...",
    generating: "ऑडियो बनाया जा रहा है...",
    audioPlayer: {
      title: "वॉयस रीडर",
      restart: "फिर से चलाएं",
      play: "पढ़ें",
      pause: "रोकें",
      speed: "गति",
      statusPlaying: "दस्तावेज़ पढ़ रहा है...",
      statusIdle: "सुनने के लिए प्ले दबाएं"
    }
  },
  mr: {
    appTitle: "DocuVoice",
    appSubtitle: "अपलोड करा, भाषांतर करा आणि ऐका.",
    selectLanguage: "भाषा निवडा",
    showMore: "सर्व दाखवा",
    showLess: "कमी दाखवा",
    history: "इतिहास",
    noHistory: "अद्याप कोणताही इतिहास नाही.",
    step1: "दस्तऐवज अपलोड करा",
    uploadPrompt: "बिल, फॉर्म किंवा दस्तऐवज अपलोड करण्यासाठी क्लिक करा",
    uploadSupport: "PDF, JPG, PNG समर्थित",
    changeFile: "फाइल बदलण्यासाठी क्लिक करा",
    optimizing: "प्रतिमेचे ऑप्टिमायझेशन होत आहे...",
    step2: "भाषा निवडा",
    generateAudio: "ऑडिओ तयार करा",
    viewHistoryPrompt: "इतिहास पाहत आहे. ऐकण्यासाठी ऑडिओ तयार करायचा?",
    summaryTitle: "सोपा सारांश",
    officialDetails: "अधिकृत दस्तऐवज तपशील",
    officialTag: "अधिकृत",
    locationTitle: "दस्तऐवज स्थान",
    openMaps: "नकाशे उघडा",
    fullTranslation: "पूर्ण अनुवादित दस्तऐवज",
    highlightTip: "जतन करण्यासाठी मजकूर हायलाइट करा",
    download: "डाउनलोड",
    actionItemsTitle: "तुम्हाला काय करायचे आहे",
    savedHighlights: "जतन केलेले हायलाइट्स",
    startOver: "पुन्हा सुरू करा",
    fastMode: "जलद",
    fastModeDesc: "छापील मजकूरासाठी सर्वोत्तम",
    detailedMode: "खोलवर विचार",
    detailedModeDesc: "गुंतागुंतीच्या फॉर्मसाठी सर्वोत्तम",
    translateBtn: "भाषांतर करा आणि मोठ्याने वाचा",
    analyzing: "दस्तऐवजाचे विश्लेषण करत आहे...",
    findingLocation: "स्थान शोधत आहे...",
    generating: "ऑडिओ तयार करत आहे...",
    audioPlayer: {
      title: "व्हॉइस रीडर",
      restart: "रीस्टार्ट",
      play: "वाचा",
      pause: "विराम",
      speed: "वेग",
      statusPlaying: "दस्तऐवज वाचत आहे...",
      statusIdle: "ऐकण्यासाठी प्ले दाबा"
    }
  },
  gu: {
    appTitle: "DocuVoice",
    appSubtitle: "અપલોડ કરો, અનુવાદ કરો અને સાંભળો.",
    selectLanguage: "ભાષા પસંદ કરો",
    showMore: "બધું બતાવો",
    showLess: "ઓછું બતાવો",
    history: "ઇતિહાસ",
    noHistory: "હજી સુધી કોઈ ઇતિહાસ નથી.",
    step1: "દસ્તાવેજ અપલોડ કરો",
    uploadPrompt: "બિલ, ફોર્મ અથવા દસ્તાવેજ અપલોડ કરવા માટે ક્લિક કરો",
    uploadSupport: "PDF, JPG, PNG સમર્થિત",
    changeFile: "ફાઇલ બદલવા માટે ક્લિક કરો",
    optimizing: "ઇમેજ ઓપ્ટિમાઇઝ થઈ રહી છે...",
    step2: "ભાષા પસંદ કરો",
    generateAudio: "ઓડિયો બનાવો",
    viewHistoryPrompt: "ઇતિહાસ જોઈ રહ્યા છીએ. સાંભળવા માટે ઓડિયો બનાવવો છે?",
    summaryTitle: "સરળ સારાંશ",
    officialDetails: "સત્તાવાર દસ્તાવેજ વિગતો",
    officialTag: "સત્તાવાર",
    locationTitle: "દસ્તાવેજનું સ્થાન",
    openMaps: "નકશા ખોલો",
    fullTranslation: "સંપૂર્ણ અનુવાદિત દસ્તાવેજ",
    highlightTip: "સાચવવા માટે ટેક્સ્ટ હાઇલાઇટ કરો",
    download: "ડાઉનલોડ",
    actionItemsTitle: "તમારે શું કરવાનું છે",
    savedHighlights: "સાચવેલ હાઇલાઇટ્સ",
    startOver: "ફરી શરૂ કરો",
    fastMode: "ઝડપી",
    fastModeDesc: "પ્રિન્ટેડ ટેક્સ્ટ માટે શ્રેષ્ઠ",
    detailedMode: "ઊંડાણપૂર્વક વિચાર",
    detailedModeDesc: "જટિલ ફોર્મ્સ માટે શ્રેષ્ઠ",
    translateBtn: "અનુવાદ કરો અને મોટેથી વાંચો",
    analyzing: "દસ્તાવેજનું વિશ્લેષણ કરી રહ્યું છે...",
    findingLocation: "સ્થાન શોધી રહ્યું છે...",
    generating: "ઓડિયો બનાવી રહ્યું છે...",
    audioPlayer: {
      title: "વોઇસ રીડર",
      restart: "રીસ્ટાર્ટ",
      play: "વાંચો",
      pause: "વિરામ",
      speed: "ઝડપ",
      statusPlaying: "દસ્તાવેજ વાંચી રહ્યું છે...",
      statusIdle: "સાંભળવા માટે પ્લે દબાવો"
    }
  },
  kn: {
    appTitle: "DocuVoice",
    appSubtitle: "ಅಪ್‌ಲೋಡ್ ಮಾಡಿ, ಅನುವಾದಿಸಿ ಮತ್ತು ಆಲಿಸಿ.",
    selectLanguage: "ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    showMore: "ಎಲ್ಲವನ್ನೂ ತೋರಿಸಿ",
    showLess: "ಕಡಿಮೆ ತೋರಿಸಿ",
    history: "ಇತಿಹಾಸ",
    noHistory: "ಇನ್ನೂ ಯಾವುದೇ ಇತಿಹಾಸವಿಲ್ಲ.",
    step1: "ದಾಖಲೆಯನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
    uploadPrompt: "ಬಿಲ್, ಫಾರ್ಮ್ ಅಥವಾ ದಾಖಲೆಯನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಲು ಕ್ಲಿಕ್ ಮಾಡಿ",
    uploadSupport: "PDF, JPG, PNG ಬೆಂಬಲಿತವಾಗಿದೆ",
    changeFile: "ಫೈಲ್ ಬದಲಾಯಿಸಲು ಕ್ಲಿಕ್ ಮಾಡಿ",
    optimizing: "ಚಿತ್ರವನ್ನು ಉತ್ತಮಗೊಳಿಸಲಾಗುತ್ತಿದೆ...",
    step2: "ಭಾಷೆಯನ್ನು ಆರಿಸಿ",
    generateAudio: "ಆಡಿಯೋ ರಚಿಸಿ",
    viewHistoryPrompt: "ಇತಿಹಾಸವನ್ನು ವೀಕ್ಷಿಸಲಾಗುತ್ತಿದೆ. ಕೇಳಲು ಆಡಿಯೋ ರಚಿಸಬೇಕೆ?",
    summaryTitle: "ಸರಳೀಕೃತ ಸಾರಾಂಶ",
    officialDetails: "ಅಧಿಕೃತ ದಾಖಲೆ ವಿವರಗಳು",
    officialTag: "ಅಧಿಕೃತ",
    locationTitle: "ದಾಖಲೆ ಸ್ಥಳ",
    openMaps: "ನಕ್ಷೆಗಳನ್ನು ತೆರೆಯಿರಿ",
    fullTranslation: "ಸಂಪೂರ್ಣ ಅನುವಾದಿತ ದಾಖಲೆ",
    highlightTip: "ಉಳಿಸಲು ಪಠ್ಯವನ್ನು ಹೈಲೈಟ್ ಮಾಡಿ",
    download: "ಡೌನ್‌ಲೋಡ್",
    actionItemsTitle: "ನೀವು ಏನು ಮಾಡಬೇಕು",
    savedHighlights: "ಉಳಿಸಲಾದ ಮುಖ್ಯಾಂಶಗಳು",
    startOver: "ಮತ್ತೆ ಪ್ರಾರಂಭಿಸಿ",
    fastMode: "ವೇಗ",
    fastModeDesc: "ಮುದ್ರಿತ ಪಠ್ಯಕ್ಕೆ ಉತ್ತಮ",
    detailedMode: "ಆಳವಾದ ತರ್ಕ",
    detailedModeDesc: "ಸಂಕೀರ್ಣ ಫಾರ್ಮ್‌ಗಳಿಗೆ ಉತ್ತಮ",
    translateBtn: "ಅನುವಾದಿಸಿ ಮತ್ತು ಗಟ್ಟಿಯಾಗಿ ಓದಿ",
    analyzing: "ದಾಖಲೆಯನ್ನು ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತಿದೆ...",
    findingLocation: "ಸ್ಥಳವನ್ನು ಹುಡುಕಲಾಗುತ್ತಿದೆ...",
    generating: "ಆಡಿಯೋ ರಚಿಸಲಾಗುತ್ತಿದೆ...",
    audioPlayer: {
      title: "ವಾಯ್ಸ್ ರೀಡರ್",
      restart: "ಮರುಪ್ರಾರಂಭಿಸಿ",
      play: "ಓದಿ",
      pause: "ವಿರಾಮ",
      speed: "ವೇಗ",
      statusPlaying: "ದಾಖಲೆಯನ್ನು ಓದಲಾಗುತ್ತಿದೆ...",
      statusIdle: "ಕೇಳಲು ಪ್ಲೇ ಒತ್ತಿರಿ"
    }
  },
  ml: {
    appTitle: "DocuVoice",
    appSubtitle: "അപ്‌ലോഡ് ചെയ്യുക, വിവർത്തനം ചെയ്യുക, കേൾക്കുക.",
    selectLanguage: "ഭാഷ തിരഞ്ഞെടുക്കുക",
    showMore: "എല്ലാം കാണിക്കുക",
    showLess: "കുറച്ച് കാണിക്കുക",
    history: "ചരിത്രം",
    noHistory: "ചരിത്രമൊന്നുമില്ല.",
    step1: "പ്രമാണം അപ്‌ലോഡ് ചെയ്യുക",
    uploadPrompt: "ബിൽ, ഫോം അല്ലെങ്കിൽ പ്രമാണം അപ്‌ലോഡ് ചെയ്യാൻ ക്ലിക്ക് ചെയ്യുക",
    uploadSupport: "PDF, JPG, PNG പിന്തുണയ്ക്കുന്നു",
    changeFile: "ഫയൽ മാറ്റാൻ ക്ലിക്ക് ചെയ്യുക",
    optimizing: "ചിത്രം ഒപ്റ്റിമൈസ് ചെയ്യുന്നു...",
    step2: "ഭാഷ തിരഞ്ഞെടുക്കുക",
    generateAudio: "ഓഡിയോ സൃഷ്ടിക്കുക",
    viewHistoryPrompt: "ചരിത്രം കാണുന്നു. കേൾക്കാൻ ഓഡിയോ സൃഷ്ടിക്കണോ?",
    summaryTitle: "ലളിതമായ സംഗ്രഹം",
    officialDetails: "ഔദ്യോഗിക രേഖാ വിവരങ്ങൾ",
    officialTag: "ഔദ്യോഗികം",
    locationTitle: "രേഖാ സ്ഥലം",
    openMaps: "മാപ്പുകൾ തുറക്കുക",
    fullTranslation: "പൂർണ്ണമായി വിവർത്തനം ചെയ്ത പ്രമാണം",
    highlightTip: "സേവ് ചെയ്യാൻ ടെക്സ്റ്റ് ഹൈലൈറ്റ് ചെയ്യുക",
    download: "ഡൗൺലോഡ്",
    actionItemsTitle: "നിങ്ങൾ ചെയ്യേണ്ട കാര്യങ്ങൾ",
    savedHighlights: "സേവ് ചെയ്ത ഹൈലൈറ്റുകൾ",
    startOver: "വീണ്ടും തുടങ്ങുക",
    fastMode: "വേഗത്തിൽ",
    fastModeDesc: "അച്ചടിച്ച വാചകത്തിന് മികച്ചത്",
    detailedMode: "വിശദമായ വിശകലനം",
    detailedModeDesc: "സങ്കീർണ്ണമായ ഫോമുകൾക്ക് മികച്ചത്",
    translateBtn: "വിവർത്തനം ചെയ്ത് ഉറക്കെ വായിക്കുക",
    analyzing: "പ്രമാണം വിശകലനം ചെയ്യുന്നു...",
    findingLocation: "സ്ഥലം കണ്ടെത്തുന്നു...",
    generating: "ഓഡിയോ സൃഷ്ടിക്കുന്നു...",
    audioPlayer: {
      title: "വോയിസ് റീഡർ",
      restart: "പുനരാരംഭിക്കുക",
      play: "വായിക്കുക",
      pause: "താൽക്കാലികമായി നിർത്തുക",
      speed: "വേഗത",
      statusPlaying: "പ്രമാണം വായിക്കുന്നു...",
      statusIdle: "കേൾക്കാൻ പ്ലേ അമർത്തുക"
    }
  },
  pa: {
    appTitle: "DocuVoice",
    appSubtitle: "ਅਪਲੋਡ ਕਰੋ, ਅਨੁਵਾਦ ਕਰੋ ਅਤੇ ਸੁਣੋ।",
    selectLanguage: "ਭਾਸ਼ਾ ਚੁਣੋ",
    showMore: "ਸਾਰੇ ਦਿਖਾਓ",
    showLess: "ਘੱਟ ਦਿਖਾਓ",
    history: "ਇਤਿਹਾਸ",
    noHistory: "ਅਜੇ ਕੋਈ ਇਤਿਹਾਸ ਨਹੀਂ ਹੈ।",
    step1: "ਦਸਤਾਵੇਜ਼ ਅਪਲੋਡ ਕਰੋ",
    uploadPrompt: "ਬਿੱਲ, ਫਾਰਮ ਜਾਂ ਦਸਤਾਵੇਜ਼ ਅਪਲੋਡ ਕਰਨ ਲਈ ਕਲਿੱਕ ਕਰੋ",
    uploadSupport: "PDF, JPG, PNG ਸਮਰਥਿਤ",
    changeFile: "ਫਾਈਲ ਬਦਲਣ ਲਈ ਕਲਿੱਕ ਕਰੋ",
    optimizing: "ਚਿੱਤਰ ਨੂੰ ਅਨੁਕੂਲ ਬਣਾਇਆ ਜਾ ਰਿਹਾ ਹੈ...",
    step2: "ਭਾਸ਼ਾ ਚੁਣੋ",
    generateAudio: "ਆਡੀਓ ਬਣਾਓ",
    viewHistoryPrompt: "ਇਤਿਹਾਸ ਦੇਖ ਰਹੇ ਹੋ। ਸੁਣਨ ਲਈ ਆਡੀਓ ਬਣਾਉਣਾ ਹੈ?",
    summaryTitle: "ਸਰਲ ਸਾਰਾਂਸ਼",
    officialDetails: "ਅਧਿਕਾਰਤ ਦਸਤਾਵੇਜ਼ ਵੇਰਵੇ",
    officialTag: "ਅਧਿਕਾਰਤ",
    locationTitle: "ਦਸਤਾਵੇਜ਼ ਸਥਾਨ",
    openMaps: "ਨਕਸ਼ੇ ਖੋਲ੍ਹੋ",
    fullTranslation: "ਪੂਰਾ ਅਨੁਵਾਦਿਤ ਦਸਤਾਵੇਜ਼",
    highlightTip: "ਸੇਵ ਕਰਨ ਲਈ ਟੈਕਸਟ ਨੂੰ ਹਾਈਲਾਈਟ ਕਰੋ",
    download: "ਡਾਊਨਲੋਡ",
    actionItemsTitle: "ਤੁਹਾਨੂੰ ਕੀ ਕਰਨਾ ਹੈ",
    savedHighlights: "ਸੇਵ ਕੀਤੇ ਹਾਈਲਾਈਟਸ",
    startOver: "ਦੁਬਾਰਾ ਸ਼ੁਰੂ ਕਰੋ",
    fastMode: "ਤੇਜ਼",
    fastModeDesc: "ਪ੍ਰਿੰਟ ਕੀਤੇ ਟੈਕਸਟ ਲਈ ਵਧੀਆ",
    detailedMode: "ਡੂੰਘੀ ਸੋਚ",
    detailedModeDesc: "ਗੁੰਝਲਦਾਰ ਫਾਰਮਾਂ ਲਈ ਵਧੀਆ",
    translateBtn: "ਅਨੁਵਾਦ ਕਰੋ ਅਤੇ ਉੱਚੀ ਆਵਾਜ਼ ਵਿੱਚ ਪੜ੍ਹੋ",
    analyzing: "ਦਸਤਾਵੇਜ਼ ਦਾ ਵਿਸ਼ਲੇਸ਼ਣ ਕੀਤਾ ਜਾ ਰਿਹਾ ਹੈ...",
    findingLocation: "ਸਥਾਨ ਲੱਭ ਰਿਹਾ ਹੈ...",
    generating: "ਆਡੀਓ ਬਣਾਇਆ ਜਾ ਰਿਹਾ ਹੈ...",
    audioPlayer: {
      title: "ਵਾਇਸ ਰੀਡਰ",
      restart: "ਰੀਸਟਾਰਟ",
      play: "ਪੜ੍ਹੋ",
      pause: "ਰੋਕੋ",
      speed: "ਗਤੀ",
      statusPlaying: "ਦਸਤਾਵੇਜ਼ ਪੜ੍ਹ ਰਿਹਾ ਹੈ...",
      statusIdle: "ਸੁਣਨ ਲਈ ਪਲੇ ਦਬਾਓ"
    }
  },
  ur: {
    appTitle: "DocuVoice",
    appSubtitle: "اپ لوڈ کریں، ترجمہ کریں اور سنیں۔",
    selectLanguage: "زبان منتخب کریں",
    showMore: "سب دکھائیں",
    showLess: "کم دکھائیں",
    history: "تاریخ",
    noHistory: "ابھی تک کوئی تاریخ نہیں ہے۔",
    step1: "دستاویز اپ لوڈ کریں",
    uploadPrompt: "بل، فارم یا دستاویز اپ لوڈ کرنے کے لیے کلک کریں",
    uploadSupport: "PDF, JPG, PNG سپورٹ شدہ",
    changeFile: "فائل تبدیل کرنے کے لیے کلک کریں",
    optimizing: "تصویر کو بہتر بنایا جا رہا ہے...",
    step2: "زبان منتخب کریں",
    generateAudio: "آڈیو بنائیں",
    viewHistoryPrompt: "تاریخ دیکھ رہے ہیں۔ سننے کے لیے آڈیو بنائیں؟",
    summaryTitle: "آسان خلاصہ",
    officialDetails: "سرکاری دستاویز کی تفصیلات",
    officialTag: "سرکاری",
    locationTitle: "دستاویز کا مقام",
    openMaps: "نقشہ کھولیں",
    fullTranslation: "مکمل ترجمہ شدہ دستاویز",
    highlightTip: "محفوظ کرنے کے لیے متن کو نمایاں کریں",
    download: "ڈاؤن لوڈ",
    actionItemsTitle: "آپ کو کیا کرنا ہے",
    savedHighlights: "محفوظ شدہ جھلکیاں",
    startOver: "دوبارہ شروع کریں",
    fastMode: "تیز",
    fastModeDesc: "پرنٹ شدہ متن کے لیے بہترین",
    detailedMode: "گہرا تجزیہ",
    detailedModeDesc: "پیچیدہ فارموں کے لیے بہترین",
    translateBtn: "ترجمہ کریں اور بلند آواز میں پڑھیں",
    analyzing: "دستاویز کا تجزیہ کیا جا رہا ہے...",
    findingLocation: "مقام تلاش کیا جا رہا ہے...",
    generating: "آڈیو بنایا جا رہا ہے...",
    audioPlayer: {
      title: "وائس ریڈر",
      restart: "دوبارہ شروع کریں",
      play: "پڑھیں",
      pause: "روکیں",
      speed: "رفتار",
      statusPlaying: "دستاویز پڑھ رہا ہے...",
      statusIdle: "سننے کے لیے پلے دبائیں"
    }
  },
  ar: {
    appTitle: "DocuVoice",
    appSubtitle: "تحميل، ترجمة، واستماع.",
    selectLanguage: "اختر لغة الإخراج",
    showMore: "عرض الكل",
    showLess: "عرض أقل",
    history: "التاريخ",
    noHistory: "لا يوجد سجل ترجمة بعد.",
    step1: "تحميل المستند",
    uploadPrompt: "انقر لتحميل فاتورة أو نموذج أو مستند",
    uploadSupport: "يدعم PDF, JPG, PNG",
    changeFile: "انقر لتغيير الملف",
    optimizing: "جارٍ تحسين الصورة...",
    step2: "اختر اللغة",
    generateAudio: "توليد الصوت",
    viewHistoryPrompt: "عرض التاريخ. توليد الصوت للاستماع؟",
    summaryTitle: "ملخص مبسط",
    officialDetails: "تفاصيل المستند الرسمي",
    officialTag: "رسمي",
    locationTitle: "موقع المستند",
    openMaps: "فتح الخرائط",
    fullTranslation: "الترجمة الكاملة",
    highlightTip: "حدد النص للحفظ",
    download: "تحميل",
    actionItemsTitle: "ما عليك القيام به",
    savedHighlights: "العناصر المحفوظة",
    startOver: "البدء من جديد",
    fastMode: "سريع",
    fastModeDesc: "الأفضل للنصوص المطبوعة",
    detailedMode: "تحليل عميق",
    detailedModeDesc: "الأفضل للنماذج المعقدة",
    translateBtn: "ترجمة وقراءة بصوت عالٍ",
    analyzing: "جارٍ تحليل المستند...",
    findingLocation: "جارٍ البحث عن الموقع...",
    generating: "جارٍ توليد الصوت...",
    audioPlayer: {
      title: "قارئ الصوت",
      restart: "إعادة التشغيل",
      play: "قراءة",
      pause: "إيقاف مؤقت",
      speed: "السرعة",
      statusPlaying: "جارٍ قراءة المستند...",
      statusIdle: "اضغط للتشغيل"
    }
  },
  zh: {
    appTitle: "DocuVoice",
    appSubtitle: "上传，翻译和收听。",
    selectLanguage: "选择输出语言",
    showMore: "显示全部",
    showLess: "显示较少",
    history: "历史",
    noHistory: "暂无翻译历史。",
    step1: "上传文档",
    uploadPrompt: "点击上传账单、表格或文档",
    uploadSupport: "支持 PDF, JPG, PNG",
    changeFile: "点击更改文件",
    optimizing: "正在优化图片...",
    step2: "选择语言",
    generateAudio: "生成音频",
    viewHistoryPrompt: "查看历史。生成音频以收听？",
    summaryTitle: "简化摘要",
    officialDetails: "官方文档详情",
    officialTag: "官方",
    locationTitle: "文档位置",
    openMaps: "打开地图",
    fullTranslation: "完整翻译文档",
    highlightTip: "高亮文本以保存",
    download: "下载",
    actionItemsTitle: "你需要做什么",
    savedHighlights: "保存的重点",
    startOver: "重新开始",
    fastMode: "快速",
    fastModeDesc: "最适合打印文本",
    detailedMode: "深度推理",
    detailedModeDesc: "最适合复杂表格",
    translateBtn: "翻译并朗读",
    analyzing: "正在分析文档...",
    findingLocation: "正在查找位置...",
    generating: "正在生成音频...",
    audioPlayer: {
      title: "语音阅读器",
      restart: "重新开始",
      play: "朗读",
      pause: "暂停",
      speed: "速度",
      statusPlaying: "正在阅读文档...",
      statusIdle: "按播放键收听"
    }
  },
  pt: {
    appTitle: "DocuVoice",
    appSubtitle: "Carregar, Traduzir e Ouvir.",
    selectLanguage: "Selecione o idioma de saída",
    showMore: "Mostrar todos",
    showLess: "Mostrar menos",
    history: "Histórico",
    noHistory: "Sem histórico ainda.",
    step1: "Carregar Documento",
    uploadPrompt: "Clique para carregar Conta, Formulário ou Documento",
    uploadSupport: "Suporta PDF, JPG, PNG",
    changeFile: "Clique para alterar arquivo",
    optimizing: "Otimizando imagem...",
    step2: "Escolher Idioma",
    generateAudio: "Gerar Áudio",
    viewHistoryPrompt: "Vendo histórico. Gerar áudio?",
    summaryTitle: "Resumo Simplificado",
    officialDetails: "Detalhes do Documento Oficial",
    officialTag: "Oficial",
    locationTitle: "Localização do Documento",
    openMaps: "Abrir Mapas",
    fullTranslation: "Tradução Completa",
    highlightTip: "Destaque texto para salvar",
    download: "Baixar",
    actionItemsTitle: "O que você precisa fazer",
    savedHighlights: "Destaques Salvos",
    startOver: "Recomeçar",
    fastMode: "Rápido",
    fastModeDesc: "Melhor para texto impresso",
    detailedMode: "Raciocínio Profundo",
    detailedModeDesc: "Melhor para formulários complexos",
    translateBtn: "Traduzir e Ler em Voz Alta",
    analyzing: "Analisando Documento...",
    findingLocation: "Encontrando Localização...",
    generating: "Gerando Áudio...",
    audioPlayer: {
      title: "Leitor de Voz",
      restart: "Reiniciar",
      play: "Ler",
      pause: "Pausa",
      speed: "Velocidade",
      statusPlaying: "Lendo documento...",
      statusIdle: "Pressione play para ouvir"
    }
  },
  bn: {
    appTitle: "DocuVoice",
    appSubtitle: "আপলোড, অনুবাদ এবং শুনুন।",
    selectLanguage: "আউটপুট ভাষা নির্বাচন করুন",
    showMore: "সব দেখান",
    showLess: "কম দেখান",
    history: "ইতিহাস",
    noHistory: "কোন ইতিহাস নেই।",
    step1: "নথি আপলোড করুন",
    uploadPrompt: "বিল, ফর্ম বা নথি আপলোড করতে ক্লিক করুন",
    uploadSupport: "PDF, JPG, PNG সমর্থিত",
    changeFile: "ফাইল পরিবর্তন করতে ক্লিক করুন",
    optimizing: "ছবি অপ্টিমাইজ করা হচ্ছে...",
    step2: "ভাষা নির্বাচন করুন",
    generateAudio: "অডিও তৈরি করুন",
    viewHistoryPrompt: "ইতিহাস দেখছেন। অডিও তৈরি করবেন?",
    summaryTitle: "সরলীকৃত সারাংশ",
    officialDetails: "অফিসিয়াল নথির বিবরণ",
    officialTag: "অফিসিয়াল",
    locationTitle: "নথির অবস্থান",
    openMaps: "মানচিত্র খুলুন",
    fullTranslation: "সম্পূর্ণ অনুবাদিত নথি",
    highlightTip: "সংরক্ষণ করতে পাঠ্য হাইলাইট করুন",
    download: "ডাউনলোড",
    actionItemsTitle: "আপনাকে যা করতে হবে",
    savedHighlights: "সংরক্ষিত হাইলাইট",
    startOver: "আবার শুরু করুন",
    fastMode: "দ্রুত",
    fastModeDesc: "মুদ্রিত পাঠ্যের জন্য সেরা",
    detailedMode: "গভীর যুক্তি",
    detailedModeDesc: "জটিল ফর্মের জন্য সেরা",
    translateBtn: "অনুবাদ করুন এবং শুনুন",
    analyzing: "নথি বিশ্লেষণ করা হচ্ছে...",
    findingLocation: "অবস্থান খোঁজা হচ্ছে...",
    generating: "অডিও তৈরি করা হচ্ছে...",
    audioPlayer: {
      title: "ভয়েস রিডার",
      restart: "রিস্টার্ট",
      play: "পড়ুন",
      pause: "বিরতি",
      speed: "গতি",
      statusPlaying: "নথি পড়া হচ্ছে...",
      statusIdle: "শুনতে প্লে চাপুন"
    }
  },
  ru: {
    appTitle: "DocuVoice",
    appSubtitle: "Загрузить, Перевести и Прослушать.",
    selectLanguage: "Выберите язык",
    showMore: "Показать все",
    showLess: "Показать меньше",
    history: "История",
    noHistory: "Истории пока нет.",
    step1: "Загрузить документ",
    uploadPrompt: "Нажмите, чтобы загрузить счет, форму или документ",
    uploadSupport: "Поддержка PDF, JPG, PNG",
    changeFile: "Нажмите, чтобы изменить файл",
    optimizing: "Оптимизация изображения...",
    step2: "Выберите язык",
    generateAudio: "Создать аудио",
    viewHistoryPrompt: "Просмотр истории. Создать аудио?",
    summaryTitle: "Упрощенное резюме",
    officialDetails: "Детали официального документа",
    officialTag: "Официально",
    locationTitle: "Местоположение документа",
    openMaps: "Открыть карты",
    fullTranslation: "Полный перевод",
    highlightTip: "Выделите текст для сохранения",
    download: "Скачать",
    actionItemsTitle: "Что нужно сделать",
    savedHighlights: "Сохраненные моменты",
    startOver: "Начать заново",
    fastMode: "Быстро",
    fastModeDesc: "Лучше для печатного текста",
    detailedMode: "Глубокий анализ",
    detailedModeDesc: "Лучше для сложных форм",
    translateBtn: "Перевести и прочитать",
    analyzing: "Анализ документа...",
    findingLocation: "Поиск местоположения...",
    generating: "Создание аудио...",
    audioPlayer: {
      title: "Голосовой читатель",
      restart: "Перезапуск",
      play: "Читать",
      pause: "Пауза",
      speed: "Скорость",
      statusPlaying: "Чтение документа...",
      statusIdle: "Нажмите play для прослушивания"
    }
  },
  de: {
    appTitle: "DocuVoice",
    appSubtitle: "Hochladen, Übersetzen und Zuhören.",
    selectLanguage: "Ausgabesprache wählen",
    showMore: "Alle anzeigen",
    showLess: "Weniger anzeigen",
    history: "Verlauf",
    noHistory: "Noch kein Verlauf.",
    step1: "Dokument hochladen",
    uploadPrompt: "Klicken zum Hochladen von Rechnung, Formular oder Dokument",
    uploadSupport: "Unterstützt PDF, JPG, PNG",
    changeFile: "Klicken zum Ändern",
    optimizing: "Bildoptimierung...",
    step2: "Sprache wählen",
    generateAudio: "Audio generieren",
    viewHistoryPrompt: "Verlauf ansehen. Audio generieren?",
    summaryTitle: "Vereinfachte Zusammenfassung",
    officialDetails: "Offizielle Dokumentendetails",
    officialTag: "Offiziell",
    locationTitle: "Dokumentenort",
    openMaps: "Karten öffnen",
    fullTranslation: "Vollständige Übersetzung",
    highlightTip: "Text markieren zum Speichern",
    download: "Herunterladen",
    actionItemsTitle: "Was Sie tun müssen",
    savedHighlights: "Gespeicherte Markierungen",
    startOver: "Neu starten",
    fastMode: "Schnell",
    fastModeDesc: "Beste für gedruckten Text",
    detailedMode: "Tiefes Denken",
    detailedModeDesc: "Beste für komplexe Formulare",
    translateBtn: "Übersetzen & Vorlesen",
    analyzing: "Dokument wird analysiert...",
    findingLocation: "Ort wird gesucht...",
    generating: "Audio wird generiert...",
    audioPlayer: {
      title: "Sprachleser",
      restart: "Neustart",
      play: "Vorlesen",
      pause: "Pause",
      speed: "Geschw.",
      statusPlaying: "Dokument wird gelesen...",
      statusIdle: "Drücken Sie Play"
    }
  },
  ja: {
    appTitle: "DocuVoice",
    appSubtitle: "アップロード、翻訳、そして聞く。",
    selectLanguage: "出力言語を選択",
    showMore: "すべて表示",
    showLess: "表示を減らす",
    history: "履歴",
    noHistory: "履歴はまだありません。",
    step1: "ドキュメントをアップロード",
    uploadPrompt: "請求書、フォーム、またはドキュメントをアップロード",
    uploadSupport: "PDF, JPG, PNG 対応",
    changeFile: "ファイル変更",
    optimizing: "画像を最適化中...",
    step2: "言語を選択",
    generateAudio: "音声を生成",
    viewHistoryPrompt: "履歴を表示中。音声を生成しますか？",
    summaryTitle: "簡単な要約",
    officialDetails: "公式文書の詳細",
    officialTag: "公式",
    locationTitle: "文書の場所",
    openMaps: "マップを開く",
    fullTranslation: "完全な翻訳",
    highlightTip: "テキストを選択して保存",
    download: "ダウンロード",
    actionItemsTitle: "やるべきこと",
    savedHighlights: "保存されたハイライト",
    startOver: "最初からやり直す",
    fastMode: "高速",
    fastModeDesc: "印刷テキストに最適",
    detailedMode: "詳細推論",
    detailedModeDesc: "複雑なフォームに最適",
    translateBtn: "翻訳して読み上げ",
    analyzing: "分析中...",
    findingLocation: "場所を検索中...",
    generating: "音声を生成中...",
    audioPlayer: {
      title: "音声リーダー",
      restart: "リスタート",
      play: "再生",
      pause: "一時停止",
      speed: "速度",
      statusPlaying: "読み上げ中...",
      statusIdle: "再生ボタンを押してください"
    }
  },
  te: {
    appTitle: "DocuVoice",
    appSubtitle: "అప్‌లోడ్ చేయండి, అనువదించండి మరియు వినండి.",
    selectLanguage: "అవుట్‌పుట్ భాషను ఎంచుకోండి",
    showMore: "అన్నీ చూపించు",
    showLess: "తక్కువ చూపించు",
    history: "చరిత్ర",
    noHistory: "ఇంకా చరిత్ర లేదు.",
    step1: "పత్రం అప్‌లోడ్ చేయండి",
    uploadPrompt: "బిల్లు, ఫారం లేదా పత్రం అప్‌లోడ్ చేయడానికి క్లిక్ చేయండి",
    uploadSupport: "PDF, JPG, PNG మద్దతు ఉంది",
    changeFile: "ఫైల్ మార్చడానికి క్లిక్ చేయండి",
    optimizing: "చిత్రం ఆప్టిమైజ్ చేస్తోంది...",
    step2: "భాషను ఎంచుకోండి",
    generateAudio: "ఆడియోను రూపొందించండి",
    viewHistoryPrompt: "చరిత్రను చూస్తున్నారు. వినడానికి ఆడియో రూపొందించాలా?",
    summaryTitle: "సరళీకృత సారాంశం",
    officialDetails: "అధికారిక పత్ర వివరాలు",
    officialTag: "అధికారిక",
    locationTitle: "పత్రం స్థానం",
    openMaps: "మ్యాప్స్ తెరవండి",
    fullTranslation: "పూర్తి అనువదించబడిన పత్రం",
    highlightTip: "సేవ్ చేయడానికి వచనాన్ని హైలైట్ చేయండి",
    download: "డౌన్‌లోడ్",
    actionItemsTitle: "మీరు ఏమి చేయాలి",
    savedHighlights: "సేవ్ చేసిన హైలైట్స్",
    startOver: "మళ్ళీ ప్రారంభించండి",
    fastMode: "వేగవంతమైన",
    fastModeDesc: "ముద్రించిన వచనానికి ఉత్తమమైనది",
    detailedMode: "లోతైన ఆలోచన",
    detailedModeDesc: "క్లిష్టమైన ఫారమ్‌లకు ఉత్తమమైనది",
    translateBtn: "అనువదించండి & వినండి",
    analyzing: "విశ్లేషస్తోంది...",
    findingLocation: "స్థానం కనుగొంటోంది...",
    generating: "ఆడియో రూపొందిస్తోంది...",
    audioPlayer: {
      title: "వాయిస్ రీడర్",
      restart: "పునఃప్రారంభించు",
      play: "చదవండి",
      pause: "పాజ్",
      speed: "వేగం",
      statusPlaying: "చదువుతోంది...",
      statusIdle: "వినడానికి ప్లే నొక్కండి"
    }
  },
  ta: {
    appTitle: "DocuVoice",
    appSubtitle: "பதிவேற்றவும், மொழிபெயர்க்கவும் மற்றும் கேட்கவும்.",
    selectLanguage: "வெளியீட்டு மொழியைத் தேர்ந்தெடுக்கவும்",
    showMore: "எல்லாம் காட்டு",
    showLess: "குறைவாக காட்டு",
    history: "வரலாறு",
    noHistory: "இன்னும் வரலாறு இல்லை.",
    step1: "ஆவணத்தை பதிவேற்றவும்",
    uploadPrompt: "பில், படிவம் அல்லது ஆவணத்தை பதிவேற்ற கிளிக் செய்யவும்",
    uploadSupport: "PDF, JPG, PNG ஆதரிக்கப்படுகிறது",
    changeFile: "கோப்பை மாற்ற கிளிக் செய்யவும்",
    optimizing: "படம் மேம்படுத்தப்படுகிறது...",
    step2: "மொழியைத் தேர்ந்தெடுக்கவும்",
    generateAudio: "ஆடியோவை உருவாக்கவும்",
    viewHistoryPrompt: "வரலாற்றைப் பார்க்கிறது. கேட்க ஆடியோ உருவாக்கவா?",
    summaryTitle: "எளிமையான சுருக்கம்",
    officialDetails: "அதிகாரப்பூர்வ ஆவண விவரங்கள்",
    officialTag: "அதிகாரப்பூர்வ",
    locationTitle: "ஆவண இருப்பிடம்",
    openMaps: "வரைபடத்தைத் திற",
    fullTranslation: "முழு மொழிபெயர்ப்பு",
    highlightTip: "சேமிக்க உரையைத் தேர்ந்தெடுக்கவும்",
    download: "பதிவிறக்க",
    actionItemsTitle: "நீங்கள் செய்ய வேண்டியவை",
    savedHighlights: "சேமிக்கப்பட்ட சிறப்பம்சங்கள்",
    startOver: "மீண்டும் தொடங்கவும்",
    fastMode: "வேகமாக",
    fastModeDesc: "அச்சிடப்பட்ட உரைக்கு சிறந்தது",
    detailedMode: "ஆழ்ந்த பகுப்பாய்வு",
    detailedModeDesc: "சிக்கலான படிவங்களுக்கு சிறந்தது",
    translateBtn: "மொழிபெயர்த்து சத்தமாக வாசிக்கவும்",
    analyzing: "ஆய்வு செய்கிறது...",
    findingLocation: "இருப்பிடத்தைத் தேடுகிறது...",
    generating: "ஆடியோ உருவாக்கப்படுகிறது...",
    audioPlayer: {
      title: "குரல் வாசகர்",
      restart: "மீண்டும் துவக்கு",
      play: "வாசி",
      pause: "இடைநிறுத்தம்",
      speed: "வேகம்",
      statusPlaying: "வாசிக்கிறது...",
      statusIdle: "கேட்க பிளேயை அழுத்தவும்"
    }
  }
};